# Generated by Django 5.0.3 on 2024-09-11 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_transaction_description_wallet_stellar_private_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='country',
            field=models.TextField(blank=True, max_length=56, null=True),
        ),
    ]
