# Generated by Django 5.0.3 on 2024-09-18 23:23

import app.models
import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_userprofile_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cryptowalletconnectsession',
            name='user',
        ),
        migrations.RemoveField(
            model_name='cryptowalletconnecttransaction',
            name='user',
        ),
        migrations.RemoveField(
            model_name='linkedaccount',
            name='user',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='description',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='mono_user_id',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='plaid_user_id',
        ),
        migrations.RemoveField(
            model_name='wallet',
            name='currency',
        ),
        migrations.AddField(
            model_name='transaction',
            name='status',
            field=models.CharField(default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='transaction',
            name='stellar_transaction_hash',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='bio',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='kyc_document',
            field=models.FileField(blank=True, null=True, upload_to='kyc_documents/'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='kyc_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(decimal_places=7, max_digits=19, validators=[app.models.validate_positive]),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='country',
            field=models.CharField(blank=True, max_length=56, null=True),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='balance',
            field=models.DecimalField(decimal_places=7, default=0.0, max_digits=19, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='stellar_private_key',
            field=models.CharField(default=django.utils.timezone.now, max_length=88),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='wallet',
            name='stellar_public_key',
            field=models.CharField(default=django.utils.timezone.now, max_length=56, unique=True),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='CryptoWalletConnectConnection',
        ),
        migrations.DeleteModel(
            name='CryptoWalletConnectSession',
        ),
        migrations.DeleteModel(
            name='CryptoWalletConnectTransaction',
        ),
        migrations.DeleteModel(
            name='LinkedAccount',
        ),
    ]
