# Generated by Django 5.0.3 on 2024-09-18 23:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_cryptowalletconnectsession_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='bio',
            new_name='dob',
        ),
    ]
